### ISSUE TITLE
都道府県と市区町村のガイドラインを分けるか？

### ISSUE THREAD

**Issue by yoshimaru7** [codeforjapan/datalaw-guideline#28]
国のガイドラインは都道府県と市区町村の2つあり、また実際問題、都道府県と市区町村では環境がかなり異なります。
そのため、勝手ガイドも2つに分けて作った方がいいのかなと思いましたが、いかがでしょうか？

**Comment by yoshimaru7** [comment]
共通する部分は本誌として纏め、別冊扱いで都道府県版と市区町村版を用意するという方法も。

**Comment by halsk** [comment]
分けた方がいいかなーと思っています。

**Comment by pshige** [comment]
小さい市区町村には無理でも都道府県には先導して策定して欲しい等担う役割が違いますよね．ぜひ分けた方がいいですよねえ．

**Comment by kozatori** [comment]
分けるときに、県が先導する領域と基礎自治体が独自にできる領域を意識しながら進めたいですね。自治体クラウド・LGWANは前者で、データ利活用は後者とか。

**Comment by kozatori** [comment]
関さん、市川さんと話して、まずは人口５万以上２０万未満の市を想定して、作成することにしたいと思います。ガイドラインのニーズとインパクトが高そうなので。
