### ISSUE TITLE
文字化けがところどころある

### ISSUE THREAD

**Issue by halsk** [codeforjapan/datalaw-guideline#3]
１章にあります。

**Comment by halsk** [comment]
#6 で、１章については修正完了。
他にもあるので見直して修正してからクローズ

**Comment by pshige** [comment]
機種依存文字は削除する形で一通りプルリクを出しましたがまだありますか？> @halsk 
ただし削ってるだけなので，もし必要なら注記をもう一度別の形で入れるべきなのかもしれません．どうでしょう？ > @hiroyuki-ichikawa

**Comment by halsk** [comment]
全て修正されていたのを確認したのでCloseします。 @pshige さん、ありがとうございました！
