### ISSUE TITLE
官デ法の略称が嫌

### ISSUE THREAD

**Issue by knj-h** [codeforjapan/datalaw-guideline#4]
官民データ法と略したい

**Comment by halsk** [comment]
そうですよねー

**Comment by norinishi** [comment]
なるほど～

**Comment by kozatori** [comment]
なるほど〜２
長い名前を付けて三文字に略すというのが役所のお作法なんですよね。シン・ゴジラの「巨災対」なんか、忠実にそれを再現してますね。多分、ジョークだけど。巨大不明生物特設災害対策本部！略して巨災対！！
というのを置いておくと「官民データ法」はいいですね。

**Comment by halsk** [comment]
確かに、「官民データ法」だと恥ずかしくはないですね。
というか、このガイドラインには「官デ法」という言葉は入ってないので、クローズしますw
